name: do_an_tot_nghiep
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  iconsax_flutter: ^1.0.0
  ionicons: ^0.2.2

  bloc: ^8.1.2
  dio: ^5.6.0
  equatable: ^2.0.5
  flutter_animate: ^4.3.0
  flutter_bloc: ^8.1.3
  go_router: ^14.2.7
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.3
  pinput: ^5.0.0
  curved_navigation_bar: ^1.0.6
  font_awesome_flutter: ^10.7.0
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1
  fl_chart: ^0.69.0
  flutter_easyloading: ^3.0.5
  tflite_flutter: ^0.11.0
  image_picker: ^1.1.2
  image: ^3.0.1
  flutter_rating: ^2.0.2
  fluttertoast: ^8.2.8
  get_it: ^8.0.2
  timeago: any
  timeago_flutter: ^3.6.0
  intl: ^0.19.0
  remove_bg: ^0.0.3
  http: ^1.2.2
  sprintf: ^7.0.0
  url_launcher: ^6.1.7
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/social_icons/
    - assets/images/home_screen/
    - assets/images/loading/
    - assets/models/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800